# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: V:/hw/Constraints/DebugCore.xdc

# XDC: V:/hw/Constraints/Implementation.xdc

# XDC: V:/hw/Constraints/Pinout.xdc

# XDC: V:/hw/Constraints/Timing.xdc

# Block Designs: V:/hw/bd/base_zynq/base_zynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq || ORIG_REF_NAME==base_zynq} -quiet] -quiet

# IP: V:/hw/bd/base_zynq/ip/base_zynq_processing_system7_0_0/base_zynq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_processing_system7_0_0 || ORIG_REF_NAME==base_zynq_processing_system7_0_0} -quiet] -quiet

# IP: V:/hw/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_rst_ps7_0_50M_0 || ORIG_REF_NAME==base_zynq_rst_ps7_0_50M_0} -quiet] -quiet

# IP: V:/hw/bd/base_zynq/ip/base_zynq_ps7_0_axi_periph_1/base_zynq_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_ps7_0_axi_periph_1 || ORIG_REF_NAME==base_zynq_ps7_0_axi_periph_1} -quiet] -quiet

# IP: V:/hw/bd/base_zynq/ip/base_zynq_xlconcat_0_0/base_zynq_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_xlconcat_0_0 || ORIG_REF_NAME==base_zynq_xlconcat_0_0} -quiet] -quiet

# IP: V:/hw/bd/base_zynq/ip/base_zynq_axi_iic_0_0/base_zynq_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_iic_0_0 || ORIG_REF_NAME==base_zynq_axi_iic_0_0} -quiet] -quiet

# IP: V:/hw/bd/base_zynq/ip/base_zynq_iobuf_0_0/base_zynq_iobuf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_iobuf_0_0 || ORIG_REF_NAME==base_zynq_iobuf_0_0} -quiet] -quiet

# IP: V:/hw/bd/base_zynq/ip/base_zynq_iobuf_0_1/base_zynq_iobuf_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_iobuf_0_1 || ORIG_REF_NAME==base_zynq_iobuf_0_1} -quiet] -quiet

# IP: V:/hw/bd/base_zynq/ip/base_zynq_xbar_0/base_zynq_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_xbar_0 || ORIG_REF_NAME==base_zynq_xbar_0} -quiet] -quiet

# IP: V:/hw/bd/base_zynq/ip/base_zynq_axistream_0_0/base_zynq_axistream_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axistream_0_0 || ORIG_REF_NAME==base_zynq_axistream_0_0} -quiet] -quiet

# IP: V:/hw/bd/base_zynq/ip/base_zynq_axi_dma_0_0/base_zynq_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_dma_0_0 || ORIG_REF_NAME==base_zynq_axi_dma_0_0} -quiet] -quiet

# IP: V:/hw/bd/base_zynq/ip/base_zynq_axi_interconnect_0_0/base_zynq_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_interconnect_0_0 || ORIG_REF_NAME==base_zynq_axi_interconnect_0_0} -quiet] -quiet

# IP: V:/hw/bd/base_zynq/ip/base_zynq_xlconcat_1_0/base_zynq_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_xlconcat_1_0 || ORIG_REF_NAME==base_zynq_xlconcat_1_0} -quiet] -quiet

# IP: V:/hw/bd/base_zynq/ip/base_zynq_xlconstant_0_0/base_zynq_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_xlconstant_0_0 || ORIG_REF_NAME==base_zynq_xlconstant_0_0} -quiet] -quiet

# IP: V:/hw/bd/base_zynq/ip/base_zynq_TARGET_C_TopLevel_Sy_0_0/base_zynq_TARGET_C_TopLevel_Sy_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_TARGET_C_TopLevel_Sy_0_0 || ORIG_REF_NAME==base_zynq_TARGET_C_TopLevel_Sy_0_0} -quiet] -quiet

# IP: v:/hw/bd/base_zynq/ip/base_zynq_auto_pc_1/base_zynq_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_pc_1 || ORIG_REF_NAME==base_zynq_auto_pc_1} -quiet] -quiet

# IP: v:/hw/bd/base_zynq/ip/base_zynq_auto_pc_0/base_zynq_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_pc_0 || ORIG_REF_NAME==base_zynq_auto_pc_0} -quiet] -quiet

# XDC: V:/hw/bd/base_zynq/base_zynq_ooc.xdc
